# 배열 재구조화
#### [Reshape]
#### [슬라이스 연산 newaxis 키워드 사용]
#### [Numpy DOC 예제]

In [26]:
import numpy as np

### [Reshape]

- `numpy.reshape(a, newshape, order='C')`
- a : shape을 변경할 대상 배열 (Array to be reshaped)
- newshape : 변경할 shape 값 (int or tuple of ints)
- 구조를 변경할때 데이터 전체 갯수와 변경할 구조의 데이터 전체 갯수가 동일 해야함
  - ex) 데이터가 10개인 1차원 배열(데이터수 10개) -> shape 이 (3,3) 으로 변경 시(데이터수 9개) 에러 발생

* 1차원 -> 2차원 재구조화

In [27]:
# 원본 배열
ori = np.arange(1,10)
print(ori)
print(ori.size)

[1 2 3 4 5 6 7 8 9]
9


In [28]:
# 변형 한 배열 : 방법1) 원본배열.reshape(변형shape) 
# 변형 shape 은 정수, 리스트, 튜플 형태로 입력
reshapeOri = ori.reshape([3,3])
print(reshapeOri)
print(reshapeOri.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [29]:
# 변형 한 배열 : 방법2) np.reshape(원본배열, newshpae=(변형shape))
reshpaeOri2 = np.reshape(ori, newshape=(3,3))
print(reshpaeOri2)
print(reshpaeOri2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


* 3차원 -> 1차원 재구조화

In [30]:
# 3차원 원본 배열
nparr = np.random.normal(loc=0, scale=0.2, size=[3,2,5])
print(nparr)
print("element size : ",nparr.size)

[[[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631]
  [ 0.05235377 -0.29985971 -0.09974467  0.17798578  0.10494596]]

 [[-0.08307164  0.11287277  0.08062484 -0.15561539 -0.01369909]
  [-0.06140265 -0.09834171  0.05903566 -0.20864631 -0.16638182]]

 [[-0.12573399 -0.20910615  0.11121456 -0.3241589  -0.00090891]
  [-0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]]]
element size :  30


In [31]:
# 1차원 변형 한 배열
reshapeNparr = nparr.reshape(30)
print(reshapeNparr)

[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631  0.05235377
 -0.29985971 -0.09974467  0.17798578  0.10494596 -0.08307164  0.11287277
  0.08062484 -0.15561539 -0.01369909 -0.06140265 -0.09834171  0.05903566
 -0.20864631 -0.16638182 -0.12573399 -0.20910615  0.11121456 -0.3241589
 -0.00090891 -0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]


In [32]:
print(nparr.reshape(-1))

[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631  0.05235377
 -0.29985971 -0.09974467  0.17798578  0.10494596 -0.08307164  0.11287277
  0.08062484 -0.15561539 -0.01369909 -0.06140265 -0.09834171  0.05903566
 -0.20864631 -0.16638182 -0.12573399 -0.20910615  0.11121456 -0.3241589
 -0.00090891 -0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]


### [슬라이스 연산 newaxis 키워드 사용]

In [33]:
# 원본 배열 확인
print(nparr)
print("nparr ndim : ",nparr.ndim)
print("nparr shape : ",nparr.shape)
print("nparr size : ",nparr.size)

[[[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631]
  [ 0.05235377 -0.29985971 -0.09974467  0.17798578  0.10494596]]

 [[-0.08307164  0.11287277  0.08062484 -0.15561539 -0.01369909]
  [-0.06140265 -0.09834171  0.05903566 -0.20864631 -0.16638182]]

 [[-0.12573399 -0.20910615  0.11121456 -0.3241589  -0.00090891]
  [-0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]]]
nparr ndim :  3
nparr shape :  (3, 2, 5)
nparr size :  30


In [34]:
# np.newaxis를 이용한 reshape
# 차원이 1개 들어남
re1 = nparr[np.newaxis, : ]
print(re1)
print("re1 ndim : ",re1.ndim)
print("re1 shape : ",re1.shape)
print("re1 size : ",re1.size)

[[[[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631]
   [ 0.05235377 -0.29985971 -0.09974467  0.17798578  0.10494596]]

  [[-0.08307164  0.11287277  0.08062484 -0.15561539 -0.01369909]
   [-0.06140265 -0.09834171  0.05903566 -0.20864631 -0.16638182]]

  [[-0.12573399 -0.20910615  0.11121456 -0.3241589  -0.00090891]
   [-0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]]]]
re1 ndim :  4
re1 shape :  (1, 3, 2, 5)
re1 size :  30


In [35]:
re2 = nparr[: ,np.newaxis]
print(re2)
print("re2 ndim : ",re2.ndim)
print("re2 shape : ",re2.shape)
print("re2 size : ",re2.size)

[[[[ 0.10115225 -0.12716019 -0.1143262  -0.14842928  0.20241631]
   [ 0.05235377 -0.29985971 -0.09974467  0.17798578  0.10494596]]]


 [[[-0.08307164  0.11287277  0.08062484 -0.15561539 -0.01369909]
   [-0.06140265 -0.09834171  0.05903566 -0.20864631 -0.16638182]]]


 [[[-0.12573399 -0.20910615  0.11121456 -0.3241589  -0.00090891]
   [-0.05873983  0.04782439 -0.02608832  0.06260299  0.08014936]]]]
re2 ndim :  4
re2 shape :  (3, 1, 2, 5)
re2 size :  30


### [Numpy DOC 예제]

In [46]:
np.newaxis is None

True

In [47]:
x = np.arange(0,3)
print(x)
print("x.ndim : ",x.ndim)
print("x.shape : ",x.shape)
print("x.size : ",x.size)

[0 1 2]
x.ndim :  1
x.shape :  (3,)
x.size :  3


In [48]:
rex1 = x[:,np.newaxis]
print(rex1)
print("rex1.ndim : ",rex1.ndim)
print("rex1.shape : ",rex1.shape)
print("rex1.size : ",rex1.size)

[[0]
 [1]
 [2]]
rex1.ndim :  2
rex1.shape :  (3, 1)
rex1.size :  3


In [49]:
rex2 = x[:,np.newaxis, np.newaxis]
print(rex2)
print("rex2.ndim : ",rex2.ndim)
print("rex2.shape : ",rex2.shape)
print("rex2.size : ",rex2.size)

[[[0]]

 [[1]]

 [[2]]]
rex2.ndim :  3
rex2.shape :  (3, 1, 1)
rex2.size :  3


In [50]:
rex3 = x[:,np.newaxis, np.newaxis, np.newaxis]
print(rex3)
print("rex3.ndim : ",rex3.ndim)
print("rex3.shape : ",rex3.shape)
print("rex3.size : ",rex3.size)

[[[[0]]]


 [[[1]]]


 [[[2]]]]
rex3.ndim :  4
rex3.shape :  (3, 1, 1, 1)
rex3.size :  3


In [51]:
print("rex3.shape : ",rex3.shape)
print("x.shape    : ",x.shape)

rex3.shape :  (3, 1, 1, 1)
x.shape    :  (3,)


In [52]:
y = rex1 * x
print(y)
print("y.ndim : ",y.ndim)
print("y.shape : ",y.shape)
print("y.size : ",y.size)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
y.ndim :  2
y.shape :  (3, 3)
y.size :  9


In [65]:
print("x                 : ",x,"     shape : ",x.shape)
print("x[np.newaxis,:]   : ",x[np.newaxis, : ],"   shape : ",x[np.newaxis, : ].shape)      
print("x[np.newaxis]     : ",x[np.newaxis],"   shape : ",x[np.newaxis].shape)
print("x[np.newaxis]     : ",x[None],"   shape : ",x[None].shape)
print("x[:,np.newaxis]   => \n",x[:,np.newaxis],"       shape : ",x[:,np.newaxis].shape)
print("\n")

x                 :  [0 1 2]      shape :  (3,)
x[np.newaxis,:]   :  [[0 1 2]]    shape :  (1, 3)
x[np.newaxis]     :  [[0 1 2]]    shape :  (1, 3)
x[np.newaxis]     :  [[0 1 2]]    shape :  (1, 3)
x[:,np.newaxis]   => 
 [[0]
 [1]
 [2]]        shape :  (3, 1)


