# 배열 연결, 분할
#### [배열 연결]
- np.concatenate
- np.vstack
- np.hstack
- np.dstack

#### [배열분할]
- np.split
- np.vsplit
- np.hsplit
- np.dsplit

In [2]:
import numpy as np

### [배열 연결]

* **np.concatenate**
  - 선언 : `numpy.concatenate((a1, a2, ...), axis=0, out=None)`
    - a1, a2, ... : 연결을 하려고 하는 배열 (튜플이나 리스트 형태로 입력)
    - axis : 연결하려는 축 방향(default : 0)
  - 연결을 위한 배열들은 동일한 **ndim(차원)과 연결 하려는 축의 원소 갯수가 동일 (shape을 통하여 확인)**해야 함

* 연결할 배열 x, y 선언

In [39]:
x = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

In [40]:
y = np.array([[9,10,11],
              [12,13,14],
              [15,16,17],
              [18,19,20]])

* axis=0을 기준(default)으로 두 배열 연결
  - x, y 는 2차원 배열
  - axis=0(행 방향)으로 연결하기 때문에 원소의 수가 동일 

In [41]:
print("x : \n",x)
print("x ndim : ",x.ndim)
print("x shape : ",x.shape)
print("x size : ",x.size)
print("----------------------")
print("y : \n",y)
print("y ndim : ",y.ndim)
print("y shape : ",y.shape)
print("y size : ",y.size)
print("----------------------")


xy = np.concatenate([x,y])
print(xy)
print("xy ndim : ",xy.ndim)
print("xy shape : ",xy.shape)
print("xy size : ",xy.size)

x : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
x ndim :  2
x shape :  (3, 3)
x size :  9
----------------------
y : 
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
y ndim :  2
y shape :  (4, 3)
y size :  12
----------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
xy ndim :  2
xy shape :  (7, 3)
xy size :  21


* 연결 axis=1을 기준으로 두배열 연결
  - x, z 는 2차원 배열
  - axis=1(열 방향)으로 연결하기 때문에 전체 행의 수가 동일  

In [43]:
z = np.array([[21,22,23,24],
              [25,26,27,28],
              [29,30,31,32]])

In [44]:
print("z : \n",z)
print("z ndim : ",z.ndim)
print("z shape : ",z.shape)
print("z size : ",z.size)
print("----------------------")
print("x : \n",x)
print("x ndim : ",x.ndim)
print("x shape : ",x.shape)
print("x size : ",x.size)
print("----------------------")


xz = np.concatenate([x,z], axis=1)
print("xz : \n",xz)
print("xz ndim : ",xz.ndim)
print("xz shape : ",xz.shape)
print("xz size : ",xz.size)

z : 
 [[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
z ndim :  2
z shape :  (3, 4)
z size :  12
----------------------
x : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
x ndim :  2
x shape :  (3, 3)
x size :  9
----------------------
xz : 
 [[ 0  1  2 21 22 23 24]
 [ 3  4  5 25 26 27 28]
 [ 6  7  8 29 30 31 32]]
xz ndim :  2
xz shape :  (3, 7)
xz size :  21


* **np.vstack**
  - 선언 : `numpy.vstack(tup)`
  - 행으로 합치기

- 1차원 배열 합치기

In [68]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr_v = np.vstack((a,b))
print(arr_v)
print("arr_v ndim : ",arr_v.ndim)
print("arr_v shape : ",arr_v.shape)
print("arr_v size : ",arr_v.size)

[[1 2 3]
 [4 5 6]]
arr_v ndim :  2
arr_v shape :  (2, 3)
arr_v size :  6


In [69]:
arr2 = np.vstack([a,b])
print(arr2)
print("arr2 ndim : ",arr2.ndim)
print("arr2 shape : ",arr2.shape)
print("arr2 size : ",arr2.size)

[[1 2 3]
 [4 5 6]]
arr2 ndim :  2
arr2 shape :  (2, 3)
arr2 size :  6


- 2차원 이상 배열 합치기
  - shape이 (**a1**,a2, ...,an-2 ,an-1, an) 일경우 두 배열은 **a1 만 제외하고 값이 동일** 해야함

In [97]:
nparr = np.random.normal(loc=0, scale=0.5, size=[3,2,4,3,7])
nparr2 = np.random.normal(loc=0, scale=0.5, size=[1,2,4,3,7])

print("===================")
print("nparr : \n",nparr)
print(nparr.ndim)
print(nparr.shape)
print("===================")
print("nparr2 : \n",nparr2)
print(nparr2.ndim)
print(nparr2.shape)
print("===================")


arr3 = np.vstack([nparr,nparr2])
print(arr3)
print("arr3 ndim : ",arr3.ndim)
print("arr3 shape : ",arr3.shape)
print("arr3 size : ",arr3.size)

nparr : 
 [[[[[-0.10306248 -0.0896441  -0.73080996  0.31108332 -0.28797488
     -0.84441245  0.76224402]
    [ 0.94681305 -0.10170843 -0.83944108 -0.29178817  0.14050466
      0.49494294  0.47175103]
    [-0.12544533 -0.53881369  1.4780458   0.24165821 -0.18941299
      0.12219334 -0.24489404]]

   [[-0.11830839  0.4242153  -0.3064167  -0.17558791 -0.27641762
     -0.13227171 -0.839646  ]
    [-1.16562312 -0.75734087  0.04898749  0.85230239 -0.49736036
      0.77764598 -0.67581202]
    [-0.29446917  0.34554378  0.40934663 -0.45584052 -0.14835212
     -0.43079442  0.33401315]]

   [[ 0.12179396 -0.70618414 -0.04152343  0.24786645  0.36266387
      0.46498664  0.62819464]
    [-0.22764588  0.25046285 -0.67292648  0.48101386  0.15435198
     -0.36081271  0.5906535 ]
    [-0.85907864 -0.24543832  0.38963461 -0.31438693  0.33813734
     -0.20737517  0.07329401]]

   [[-0.23348861 -0.25312978  0.97603844 -0.12038282  0.71382889
     -0.4243109   0.00253332]
    [-0.42084624  0.32190853 -0.34

* **np.hstack**
  - 선언 : `numpy.hstack(tup)`
  - 열로 합치기

* 1차원 배열 합치기

In [66]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr_h = np.hstack((a,b))
print(arr_h)
print("arr_h ndim : ",arr_h.ndim)
print("arr_h shape : ",arr_h.shape)
print("arr_h size : ",arr_h.size)

[1 2 3 4 5 6]
arr ndim :  1
arr shape :  (6,)
arr size :  6


- 2차원 이상 배열 합치기
  - shape이 (a1,**a2**, ...,an-2 ,an-1, an) 일경우 두 배열은 **a2 만 제외하고 의 값이 동일** 해야함

In [91]:
nparr3 = np.random.normal(loc=0, scale=0.5, size=[3,2,2,5,4])
nparr4 = np.random.normal(loc=0, scale=0.5, size=[3,1,2,5,4])

print("===================")
print("nparr3 : \n",nparr3)
print(nparr3.ndim)
print(nparr3.shape)
print("===================")
print("nparr4 : \n",nparr4)
print(nparr4.ndim)
print(nparr4.shape)
print("===================")


arr4 = np.hstack([nparr3,nparr4])
print(arr4)
print("arr4 ndim : ",arr4.ndim)
print("arr4 shape : ",arr4.shape)
print("arr4 size : ",arr4.size)

nparr3 : 
 [[[[[ 0.43844551  0.20493228 -0.13074403 -0.53964468]
    [-0.01038661  0.65058159  0.3730558  -0.30265401]
    [ 0.05089444 -1.14150136 -0.32348814 -0.81293923]
    [ 0.78164512 -0.51999641  0.53436502 -0.24106771]
    [-0.12202101  0.23398437 -1.01252647  0.05777197]]

   [[ 0.18006547  0.77753759 -0.57527263  0.77222279]
    [-0.47154497 -0.50840307 -0.30236557  0.27359269]
    [-0.36178593  0.34856485  0.3643096  -0.23153593]
    [-0.6386661  -0.82700381  0.50324289 -1.0728212 ]
    [ 0.24614933  0.66811853  0.36184785 -0.23148105]]]


  [[[ 0.20957306 -0.2075535   0.35002532 -0.03894947]
    [ 0.55674931 -0.32234668 -0.60384146  0.07498148]
    [ 0.19694968  0.33747478 -1.78486827 -0.47918829]
    [ 0.76307675  0.65281632  0.1043643  -0.89175183]
    [-0.24993771  0.72582473  0.86046788 -0.44527426]]

   [[-0.20431037 -0.7362397  -0.50428946  0.64987896]
    [ 0.44942517 -0.30001126 -0.33271686 -0.91466705]
    [-0.22011784  0.01219902  0.38650629 -0.53860641]
    [ 0.7

* **np.dstack**
  - 선언 : `numpy.dstack(tup)`
  - 깊이 방향(각각 배열의 원소)으로 합치기

In [99]:
a = np.array([1,2,3])
b = np.array([4,5,6])
arr_d = np.dstack((a,b))
print(arr_d)
print("arr_d ndim : ",arr_d.ndim)
print("arr_d shape : ",arr_d.shape)
print("arr_d size : ",arr_d.size)

[[[1 4]
  [2 5]
  [3 6]]]
arr_d ndim :  3
arr_d shape :  (1, 3, 2)
arr_d size :  6


- 2차원 이상 배열 합치기
  - shape이 (a1,a2,**a3**, ...,an-2 ,an-1, an) 일경우 두 배열은 **a3 만 제외하고 의 값이 동일** 해야함

In [117]:
nparr5 = np.random.normal(loc=0, scale=0.5, size=[3,2,1,2,3])
nparr6 = np.random.normal(loc=0, scale=0.5, size=[3,2,4,2,3])

print("===================")
print("nparr5 : \n",nparr5)
print(nparr5.ndim)
print(nparr5.shape)
print("===================")
print("nparr6 : \n",nparr6)
print(nparr6.ndim)
print(nparr6.shape)
print("===================")


arr5 = np.dstack([nparr5,nparr6])
print(arr5)
print("arr5 ndim : ",arr5.ndim)
print("arr5 shape : ",arr5.shape)
print("arr5 size : ",arr5.size)

nparr5 : 
 [[[[[ 0.42871208  0.91188645  0.00636661]
    [-0.14649802  0.00870485 -0.47579013]]]


  [[[ 0.30073163  0.99172646 -0.70223822]
    [-0.16125086 -0.89903161 -0.05146419]]]]



 [[[[ 0.41651056  0.14982317 -0.58282578]
    [ 0.07204673  0.69951584 -0.10680044]]]


  [[[ 0.13629509  0.0319888  -0.30787561]
    [-0.10109996 -0.17155776 -0.39236094]]]]



 [[[[ 0.20717234  0.82926386  0.29816704]
    [ 0.69106898  0.33984265 -0.82931549]]]


  [[[ 0.08026669 -0.52712411  0.79471515]
    [ 0.99454387 -1.12832214  0.01775898]]]]]
5
(3, 2, 1, 2, 3)
nparr6 : 
 [[[[[-0.42544046  0.40726377 -0.33661485]
    [-0.34780487  1.30771266 -1.06267146]]

   [[ 0.74592189 -0.08150936  0.02052765]
    [-0.22787328 -0.08281587  0.34560114]]

   [[-0.37958616  0.03873145  0.48450598]
    [-0.06688887 -0.11309652 -0.09492682]]

   [[-0.34194275 -0.04502547 -0.40288477]
    [-0.30212408 -0.50384122 -1.02481056]]]


  [[[ 0.32299352  0.00637123  0.01737847]
    [ 0.49499335 -0.40865384 -0.32187868

### [배열 분할]

* **np.split**
  - 선언 : `numpy.split(ary, indices_or_sections, axis=0)`
    - ary : 분할 하려는 배열 
    - indices_or_sections(integer) : 분할 하려는 지점   
  - 정수 입력시 입력한 정수값의 갯수 만큼 분할
  - 배열 입력시 분할할 index 지점을 입력

In [72]:
# 분할 할 배열 선언
ori_arr = np.array([[1,2],
                    [3,4],
                    [5,6],
                    [7,8]])
print(ori_arr)
print("ori_arr ndim : ",ori_arr.ndim)
print("ori_arr shape : ",ori_arr.shape)
print("ori_arr size : ",ori_arr.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
ori_arr ndim :  2
ori_arr shape :  (4, 2)
ori_arr size :  8


* **분할 할 갯수 입력(integer)**
  * 배열을 분할할 갯수로 나눴을때 나머지가 생기지 않을 정수만 입력 가능

* 분할한 배열 Return 방법1

In [73]:
sp_a, sp_b, sp_c, sp_d = np.split(ori_arr, 4)
print(sp_a)
print("____\n")
print(sp_b)
print("____\n")
print(sp_c)
print("____\n")
print(sp_d)


[[1 2]]
____

[[3 4]]
____

[[5 6]]
____

[[7 8]]


* 분할한 배열 Return 방법2

In [74]:
arr = np.split(ori_arr,4)
for elem in arr:
    print(elem)
    print("____\n")

[[1 2]]
____

[[3 4]]
____

[[5 6]]
____

[[7 8]]
____



* **분할 할 지점의 인덱스를 리스트로 입력**
  * 배열의 총 인덱스를 넘어가는 인덱스 부분은 공백으로 리턴됨

In [75]:
arr = np.split(ori_arr, [1,2,3,4,6])
for elem in arr:
    print(elem)
    print("____\n")

[[1 2]]
____

[[3 4]]
____

[[5 6]]
____

[[7 8]]
____

[]
____

[]
____



In [76]:
# 원본 배열 선언
ori_arr2 = np.random.normal(loc=0, scale=1, size=[3,2,5])
print(ori_arr2)
print("ori_arr2 ndim : ",ori_arr2.ndim)
print("ori_arr2 shape : ",ori_arr2.shape)
print("ori_arr2 size : ",ori_arr2.size)

[[[ 0.19853709  0.32116314  0.19203126 -0.73021249  0.3423791 ]
  [-0.00711257 -0.89719629  0.39491508  1.07290065 -0.13114291]]

 [[-0.4655381   0.92481127  0.50336916 -0.00330438  0.32039131]
  [ 0.80269099  1.22929465  0.83466752  0.88220819 -0.14663008]]

 [[ 0.84585634 -0.0413827  -0.45347173  1.2716267  -0.54244704]
  [ 0.41790547 -0.3273629  -1.52736833 -1.23106631  0.08141322]]]
ori_arr2 ndim :  3
ori_arr2 shape :  (3, 2, 5)
ori_arr2 size :  30


In [77]:
# 인덱스로 분할
for elem in np.split(ori_arr2, [1,2]):
    print(elem)
    print("ndim : ",elem.ndim)
    print("shape : ",elem.shape)
    print("size : ",elem.size)
    print("____\n")
    

[[[ 0.19853709  0.32116314  0.19203126 -0.73021249  0.3423791 ]
  [-0.00711257 -0.89719629  0.39491508  1.07290065 -0.13114291]]]
ndim :  3
shape :  (1, 2, 5)
size :  10
____

[[[-0.4655381   0.92481127  0.50336916 -0.00330438  0.32039131]
  [ 0.80269099  1.22929465  0.83466752  0.88220819 -0.14663008]]]
ndim :  3
shape :  (1, 2, 5)
size :  10
____

[[[ 0.84585634 -0.0413827  -0.45347173  1.2716267  -0.54244704]
  [ 0.41790547 -0.3273629  -1.52736833 -1.23106631  0.08141322]]]
ndim :  3
shape :  (1, 2, 5)
size :  10
____



* **np.vsplit**
  - 선언 : `numpy.vsplit(ary, indices_or_sections)`
    - ary : 분할 하려는 배열 
    - indices_or_sections(integer) : 분할 하려는 지점   
  - 정수 입력시 입력한 정수값의 갯수 만큼 분할
  - 배열 입력시 분할할 index 지점을 입력

In [78]:
# 분할 할 배열 선언
arr_ori_v = np.array([[  0.,   1.,   2.,   3.],
                      [  4.,   5.,   6.,   7.],
                      [  8.,   9.,  10.,  11.],
                      [ 12.,  13.,  14.,  15.]])
print(arr_ori_v)
print("ndim : ",arr_ori_v.ndim)
print("shape : ",arr_ori_v.shape)
print("size : ",arr_ori_v.size)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
ndim :  2
shape :  (4, 4)
size :  16


* **분할 할 갯수 입력(integer)**

In [80]:
result = np.vsplit(arr_ori_v,2)
for elem in result:
    print(elem)
    print("____\n")

[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
____

[[ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
____



* **분할 할 지점의 인덱스를 리스트로 입력**

In [81]:
result = np.vsplit(arr_ori_v,[1,2,3,4])
for elem in result:
    print(elem)
    print("____\n")

[[0. 1. 2. 3.]]
____

[[4. 5. 6. 7.]]
____

[[ 8.  9. 10. 11.]]
____

[[12. 13. 14. 15.]]
____

[]
____



* **np.hsplit**
  - 선언 : `numpy.hsplit(ary, indices_or_sections)`
    - ary : 분할 하려는 배열 
    - indices_or_sections(integer) : 분할 하려는 지점   
  - 정수 입력시 입력한 정수값의 갯수 만큼 분할
  - 배열 입력시 분할할 index 지점을 입력

In [82]:
# 분할 할 배열 선언
arr_ori_h = np.array([[  0.,   1.,   2.,   3.],
                      [  4.,   5.,   6.,   7.],
                      [  8.,   9.,  10.,  11.],
                      [ 12.,  13.,  14.,  15.]])
print(arr_ori_h)
print("ndim : ",arr_ori_h.ndim)
print("shape : ",arr_ori_h.shape)
print("size : ",arr_ori_h.size)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
ndim :  2
shape :  (4, 4)
size :  16


* **분할 할 갯수 입력(integer)**

In [84]:
result = np.hsplit(arr_ori_h,4)
for elem in result:
    print(elem)
    print("____\n")

[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
____

[[ 1.]
 [ 5.]
 [ 9.]
 [13.]]
____

[[ 2.]
 [ 6.]
 [10.]
 [14.]]
____

[[ 3.]
 [ 7.]
 [11.]
 [15.]]
____



* **분할 할 지점의 인덱스를 리스트로 입력**

In [85]:
result = np.hsplit(arr_ori_h,[1,2,3,4])
for elem in result:
    print(elem)
    print("____\n")

[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
____

[[ 1.]
 [ 5.]
 [ 9.]
 [13.]]
____

[[ 2.]
 [ 6.]
 [10.]
 [14.]]
____

[[ 3.]
 [ 7.]
 [11.]
 [15.]]
____

[]
____



* **np.dsplit**
  - 선언 : `numpy.dsplit(ary, indices_or_sections)`
    - ary : 분할 하려는 배열 
    - indices_or_sections(integer) : 분할 하려는 지점   
  - 정수 입력시 입력한 정수값의 갯수 만큼 분할
  - 배열 입력시 분할할 index 지점을 입력

In [91]:
# 분할 할 배열 선언
arr_ori_d = np.array([[[  0.,   1.,   2.,   3.],
                       [  4.,   5.,   6.,   7.]],
                      [[  8.,   9.,  10.,  11.],
                       [ 12.,  13.,  14.,  15.]]])
print(arr_ori_d)
dsasd

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
ndim :  3
shape :  (2, 2, 4)
size :  16


* **분할 할 갯수 입력(integer)**

In [92]:
result = np.dsplit(arr_ori_d,4)
for elem in result:
    print(elem)
    print("____\n")

[[[ 0.]
  [ 4.]]

 [[ 8.]
  [12.]]]
____

[[[ 1.]
  [ 5.]]

 [[ 9.]
  [13.]]]
____

[[[ 2.]
  [ 6.]]

 [[10.]
  [14.]]]
____

[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]
____



* **분할 할 지점의 인덱스를 리스트로 입력**

In [95]:
result = np.dsplit(arr_ori_d,[1,2,3,4])
for elem in result:
    print(elem)
    print("____\n")

[[[ 0.]
  [ 4.]]

 [[ 8.]
  [12.]]]
____

[[[ 1.]
  [ 5.]]

 [[ 9.]
  [13.]]]
____

[[[ 2.]
  [ 6.]]

 [[10.]
  [14.]]]
____

[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]
____

[]
____

