# 브로드케스팅 연산

- **브로드케스팅(Broadcasting)**
  - 벡터화 연산의 또 다른 방법
  - 다른 크기의 배열에 이항 UFuncs(사칙연산 등)를 적용하기 위한 규칙
  - **서로 다른 크기의 배열에서 수행 가능**

In [15]:
import numpy as np

###### 예) 1차원 배열 덧셈

In [16]:
a = np.array([1,2,3])
b = np.array([4,4,4])
print(a+b)

[5 6 7]


###### 예) 1차원 배열 , 스칼라 덧셈

In [17]:
# 브로드케스팅을 이용한 덧셈연산
n = 6
print(n)
print(type(n))
# 배열 + 스칼라
print(a + n)

6
<class 'int'>
[7 8 9]


* n=6 을 덧셈을 하기 위하여 a와 같은 크기의 배열로 늘려서 연산을 하도록 함
* n=[6,6,6] 으로 늘린다고 생각하며 됨

### 브로드케스팅 규칙
- 규칙 1. 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을 1로 채움
  - (2,3,4) 배열과 (5,6) 배열이 있으면 (5,6)배열의 왼쪽에 1을 채워서 **(1,5,6)으로 바꾸고 연산함**
  - 차원을 늘리는 방법
    1. reshape 이용
    2. np.newaxis 이용 => arr[np.newaxis, : ]


- 규칙 2. 두 배열의 형상이 어떤 차원에서도 일치 하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어남 
  - (2,3,4) 배열과 (1,3,4) 배열이 있으면 첫번째 차원이 다르기 때문에 형상이 1인 두번째 배열을 첫번째 배열의 형상인 2로 **(2,3,4)로 늘림**
 

- 규칙 3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생

###### 예) 규칙 1, 2를 적용한 결과 (배열 1개만 변형)

In [18]:
M = np.ones((2, 3))
a = np.arange(3)
print("M\n",M)
print("a\n",a)
print("\n")
print("M shape : ",M.shape)
print("a shape : ",a.shape)

M
 [[1. 1. 1.]
 [1. 1. 1.]]
a
 [0 1 2]


M shape :  (2, 3)
a shape :  (3,)


- a shape 이 더 작은 차원을 가지고 있기 때문에 앞쪽을 1로 채움(reshape 이용) <=**규칙1 적용**
  - shape (3,) -> shaep (1,3)

In [19]:
a_1 = a.reshape([1,3])
print(a_1)
print("a_1 shape : ",a_1.shape)

[[0 1 2]]
a_1 shape :  (1, 3)


* np.newaxis 사용하여 차원 늘릴 수 있음 <= **규칙1적용시**

In [20]:
a_newaxis = a[np.newaxis, : ]
print(a_newaxis)
print("a_newaxis ndim : ",a_newaxis.ndim)
print("a_newaxis shape : ",a_newaxis.shape)

[[0 1 2]]
a_newaxis ndim :  2
a_newaxis shape :  (1, 3)


* 첫번째 차원이 2,1로 다르기 때문에 차원을 일치하도록 동일한 값으로 늘림 <= **규칙2 적용**
  * shape(1,3) -> shape(2,3)

In [21]:
a_1_2 = np.concatenate([a_1,a_1])
print(a_1_2)
print("a_1_2 shape : ",a_1_2.shape)

[[0 1 2]
 [0 1 2]]
a_1_2 shape :  (2, 3)


In [22]:
# 직접 바꾼 형태의 배열로 연산한 결과
print(M + a_1_2)

[[1. 2. 3.]
 [1. 2. 3.]]


In [23]:
# 브로드케스팅 적용된 결과
print(M+a)

[[1. 2. 3.]
 [1. 2. 3.]]


###### 예) 규칙 1, 2를 적용한 결과 (배열 2개 모두 변형)

In [24]:
arr1 = np.arange(3).reshape([3,1])
arr2 = np.arange(3)
print("arr1\n",arr1)
print("arr2\n",arr2)
print("\n")
print("arr1 shape : ",arr1.shape)
print("arr2 shape : ",arr2.shape)

arr1
 [[0]
 [1]
 [2]]
arr2
 [0 1 2]


arr1 shape :  (3, 1)
arr2 shape :  (3,)


- arr2 이 더 작은 차원을 가지고 있기 때문에 앞쪽을 1로 채움(reshape 이용) <=**규칙1 적용**
  - shape (3,) -> shaep (1,3)

In [25]:
arr2_1 = arr2.reshape([1,3])
print(arr2_1)
print("shape : ",arr2_1.shape)

[[0 1 2]]
shape :  (1, 3)


* arr1 shape : (3,1)
* arr2_1 shape : (1,3)

* arr1의 1, arr2_1의 1의 차원을 서로 맞춰 줌 <= **규칙2 적용**
  * arr1   : shape(3,1) -> shape(3,3)
  * arr2_1 : shape(1,3) -> shape(3,3)


In [26]:
arr1_2 = np.concatenate([arr1,arr1,arr1],axis=1)
print(arr1_2)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [27]:
arr2_1_2 = np.concatenate([arr2_1,arr2_1,arr2_1])
print(arr2_1_2)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [28]:
# 직접 바꾼 형태의 배열로 연산한 결과
print(arr1_2 + arr2_1_2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [29]:
# 브로드케스팅 적용된 결과
print(arr1 + arr2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


###### 예) 규칙 3

In [30]:
M = np.ones((3, 2))
a = np.arange(3)

In [31]:
print(M+a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

* 규칙 1 적용 변형 : a shape : (3, ) -> (1,3)
* 규칙 2 적용 비교 
  * M shape : (3,2)
  * a shape : (1,3)
  * **M의 shape 가 (3,2)에서 2 이기 때문에 규칙 2의 1이 아닌 값이라 에러가 발생**


#### 규칙 1을 적용할때 차원을 왼쪽에 늘리는 것이 아니고 오른쪽으로 늘린다면??
* **브로드케스팅은 이런 방식으로 동작하지 않음**

In [32]:
print("M\n",M)
print("n\n",a)
print("\n")
print("M shape : ",M.shape)
print("a shape : ",a.shape)

M
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
n
 [0 1 2]


M shape :  (3, 2)
a shape :  (3,)


* a 배열의 오른쪽으로 차원을 늘리고 규칙 2를 적용한다면....

In [33]:
a_addRightDim = a[ : , np.newaxis]
print(a_addRightDim)
print("a_addRightDim ndim : ",a_addRightDim.ndim)
print("a_addRightDim shape : ",a_addRightDim.shape)

[[0]
 [1]
 [2]]
a_addRightDim ndim :  2
a_addRightDim shape :  (3, 1)


In [35]:
# 규칙 2를 적용하여 1인 차원을 다른 배열의 차원과 동일하게 해주기 위하여 데이터 늘림
a_addRightDim_2 = np.hstack([a_addRightDim, a_addRightDim])
print(a_addRightDim_2)
print("a_addRightDim_2 ndim : ",a_addRightDim_2.ndim)
print("a_addRightDim_2 shape : ",a_addRightDim_2.shape)

[[0 0]
 [1 1]
 [2 2]]
a_addRightDim_2 ndim :  2
a_addRightDim_2 shape :  (3, 2)


In [36]:
# 직접 바꾼 형태의 배열로 연산한 결과
print(M+a_addRightDim_2)

[[1. 1.]
 [2. 2.]
 [3. 3.]]


In [37]:
# 브로드케스팅 적용된 결과
print(M+a_addRightDim)

[[1. 1.]
 [2. 2.]
 [3. 3.]]


* 규칙1은 왼쪽으로 차원을 늘리는 것이지만 오늘쪽으로 늘려서 브로드케스팅을 적용 할 수 있으나...
* **브로드케스팅의 동작 방식은 아니다**

# 브로드케스팅 연산 실전연습
###### 예) 배열을 중앙 정렬하기

In [41]:
X = np.random.random((10, 3))
print(X)
print(X.ndim)
print(X.shape)

[[0.84753058 0.39609429 0.85551586]
 [0.54510334 0.99852398 0.51105227]
 [0.12992009 0.18950895 0.47858539]
 [0.52955211 0.56414674 0.66028312]
 [0.28805371 0.87931212 0.87063195]
 [0.71248486 0.10103614 0.39511667]
 [0.82871027 0.22180642 0.94396353]
 [0.41711232 0.58652581 0.15539907]
 [0.33286357 0.07589971 0.60077712]
 [0.33597395 0.67242758 0.17556699]]
2
(10, 3)


In [43]:
Xmean = X.mean(0)
print(Xmean)
print(Xmean.ndim)
print(Xmean.shape)

[0.49673048 0.46852817 0.5646892 ]
1
(3,)


In [44]:
# 브로드케스팅됨
X_centered = X - Xmean
# (10,3)
# (3,)   ->   (1,3)   ->   (10,3)
#       규칙1         규칙2

In [48]:
print(X_centered.mean(0))

[-5.55111512e-17 -1.11022302e-17  0.00000000e+00]
