# axis 축

In [2]:
import numpy as np

- sum
  - `numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)`

In [3]:
x = np.array([[[ 0,  1,  2],
               [ 3,  4,  5],
               [ 6,  7,  8]],
              [[ 9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]],
              [[18, 19, 20],
               [21, 22, 23],
               [24, 25, 26]]])

print(x)
print("x ndim : ",x.ndim)
print("x shape : ",x.shape)
print("x size : ",x.size)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
x ndim :  3
x shape :  (3, 3, 3)
x size :  27


* 모든 원소 의 합

In [4]:
result = 0
for i in range(27):
    result += i
print(result)

351


In [5]:
sum = x.sum()
print(sum)

351


* **axis=-1 합**
  * axis = -1 은 배열의 가장 마지막 차원의 수를 의미함 
  * 예제에서 3차원 예제이기 때문에 -1은 2와 동일함


In [13]:
print("x \n",x)
print("\n")
result = np.sum(x, axis=-1)
print("axis=-1 : \n",result)
print("ndim : ",result.ndim)
print("shape : ", result.shape)
print("size : ",result.size)

x 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


axis=-1 : 
 [[ 3 12 21]
 [30 39 48]
 [57 66 75]]
ndim :  2
shape :  (3, 3)
size :  9


* **axis=0 합**
  - 27 = 0 + 9 + 18
  - 39 = 4 + 13 + 22
  - 51 = 8 + 17 + 26

In [12]:
print(x)
print("\n")
sum_0 = x.sum(axis=0)
print("axis=0 : \n",sum_0)
print("ndim : ",sum_0.ndim)
print("shape : ",sum_0.shape)
print("size : ",sum_0.size)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


axis=0 : 
 [[27 30 33]
 [36 39 42]
 [45 48 51]]
ndim :  2
shape :  (3, 3)
size :  9


In [35]:
# keyword(axis=)를 생략 가능
print("axis=0 : \n",sum_0)
print("ndim : ",sum_0.ndim)
print("shape : ",sum_0.shape)
print("size : ",sum_0.size)

axis=0 : 
 [[27 30 33]
 [36 39 42]
 [45 48 51]]
ndim :  2
shape :  (3, 3)
size :  9


* **axis=1 합**
  - 9 = 0 + 3 + 6
  - 12 = 1 + 4 + 7
  - 15 = 2 + 5 + 8  
  - 36 = 9 + 12 + 15
  - 39 = 10 + 13 + 16
  - 42 = 11 + 14 + 17  
  - 63 = 18 + 21 + 24 
  - 66 = 19 + 22 + 25 
  - 69 = 20 + 23 + 69 

In [36]:
print(x)
print("\n")
sum_1 = x.sum(axis=1)
print("axis=1 : \n",sum_1)
print("ndim : ",sum_1.ndim)
print("shape : ",sum_1.shape)
print("size : ",sum_1.size)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


axis=1 : 
 [[ 9 12 15]
 [36 39 42]
 [63 66 69]]
ndim :  2
shape :  (3, 3)
size :  9


* **axis=2 합** 
  - 3 = 0+1+2
  - 12 = 3+4+5
  - 21 = 6+7+8
  - 30 = 9+10+11
  - 39 = 12+13+14
  - 48 = 15+16+17
  - 57 = 18+19+20
  - 66 = 21+22+23
  - 75 = 24+25+26

In [38]:
print(x)
print("\n")
sum_2 = x.sum(axis=2)
print("axis= 2 : \n",sum_2)
print("ndim : ",sum_2.ndim)
print("shape : ",sum_2.shape)
print("size : ",sum_2.size)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


axis= 2 : 
 [[ 3 12 21]
 [30 39 48]
 [57 66 75]]
ndim :  2
shape :  (3, 3)
size :  9


In [40]:
# x 배열의 차원이 3차원 이기때문에 axis 는 2까지 사용 가능
print(x.sum(axis=3))

AxisError: axis 3 is out of bounds for array of dimension 3

In [43]:
y=np.array([[1,2,3],
            [4,5,6]])
print(y.sum(axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [44]:
print(y.sum(axis=1))

[ 6 15]


In [45]:
print(y.sum(axis=0))

[5 7 9]
